receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

processors:
  resourcedetection:
    detectors: [env,system]
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  otlphttp/oracleapm:
    endpoint: "<apmendpoint>/20200101/opentelemetry"
    headers:
      Authorization: "dataKey <privatedatakey>"
service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, resourcedetection]
      exporters: [otlphttp/oracleapm]
